### PR TITLE
Fix #25: can't decode 32 bytes of 0s

### LINKED ISSUE #25: Doesn't decode 32 bytes of 0x00
Due to line `let mut output = vec![0; (self.input.as_ref().len() / 8 + 1) * 6];` in `into_vec` it only allocates 30 bytes (encoding is `11111111111111111111111111111111` which has length of 32).

Simple unit test:
```
let data = vec![0; 32];
let s = b58::encode(&data).to_string();
let result = b58::decode(&s).into_vec().unwrap(); // crash
assert_eq!(result, data);
```

### PR DESCRIPTION
**Pull request by ilblackdragon**

### CODE REVIEW

File: src/decode.rs [hunk 1]
```diff
@@ -86,7 +86,7 @@ impl<'a, I: AsRef<[u8]>> DecodeBuilder<'a, I> {
     /// ```
     ///
     pub fn into_vec(self) -> Result<Vec<u8>, DecodeError> {
-        let mut output = vec![0; (self.input.as_ref().len() / 8 + 1) * 6];
+        let mut output = vec![0; std::cmp::max(self.input.as_ref().len(), (self.input.as_ref().len() / 8 + 1) * 6)];
```
Comment (Nemo157) [inline src/decode.rs]:
```suggestion
        let mut output = vec![0; self.input.as_ref().len()];
```

The decoded length is guaranteed to be at most the encoded length (for this worst case of all zeros). There's no need to calculate the estimated length since that's going to be shorter (other than the cases where it was already over-estimating the length).
